annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-ui-plugin-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux, windows
  catalog.cattle.io/scope: management
  catalog.cattle.io/ui-component: plugins
  catalog.cattle.io/rancher-version: '>= v2.14.0'
  catalog.cattle.io/display-name: Longhorn
  catalog.cattle.io/ui-extensions-version: '>= 3.0.0 < 4.0.0'
apiVersion: v2
appVersion: 0.1.0
description: Rancher UI Extension for Longhorn
name: longhorn
type: application
version: 0.1.0
icon: >-
  https://raw.githubusercontent.com/rancher/longhorn-ui-extension/main/pkg/longhorn/icon.png
