#!/bin/bash
set -e

# Get the directory of the script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Project root is one level up from scripts/
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Source directory
AGENTS_DIR="${PROJECT_ROOT}/docs/agents"

# Destination file
OUTPUT_FILE="${PROJECT_ROOT}/AGENTS.md"

echo "Generating ${OUTPUT_FILE}..."

# Header
cat > "${OUTPUT_FILE}" << 'EOF'
# Longhorn UI Extension - AI Agent Guide

> This file is generated by running `yarn agents:generate`.
> To modify, edit files in `docs/agents/` and regenerate.

EOF

# Insert all agent files in order
if [ -d "$AGENTS_DIR" ]; then
    for file in "$AGENTS_DIR"/*.md; do
        if [ -f "$file" ]; then
            cat "$file"
            echo ""
            echo ""
        fi
    done
fi >> "${OUTPUT_FILE}"

# Footer
cat >> "${OUTPUT_FILE}" << 'EOF'
---

**Last Generated**: $(date '+%Y-%m-%d %H:%M:%S')
**Version**: 1.0
EOF

# Keep CLAUDE.md and GEMINI.md aligned with AGENTS.md
ln -sf ./AGENTS.md "${PROJECT_ROOT}/CLAUDE.md"
ln -sf ./AGENTS.md "${PROJECT_ROOT}/GEMINI.md"

echo "Done. Generated ${OUTPUT_FILE}"
echo ""
echo "Next steps:"
echo "  1. Review the generated AGENTS.md"
echo "  2. Verify symlinks: ls -l CLAUDE.md GEMINI.md AGENTS.md"
echo "  3. Commit all files: git add docs/agents/ AGENTS.md CLAUDE.md GEMINI.md scripts/generate-agents.sh"
