import { STATE, NAME as NAME_COL, AGE, IMAGE_NAME } from '@shell/config/table-headers';

export const NODES_HEADER = [
  {
    name: 'status',
    label: 'Status',
    value: 'nodeStatus',
    sort: ['nodeStatus.stateDisplay'],
    search: ['nodeStatus.stateDisplay'],
    formatter: 'NodeStatus',
    width: 120,
  },
  {
    ...NAME_COL,
    width: 200,
  },
  {
    name: 'ready',
    labelKey: 'longhorn.node.table.header.ready',
    search: "$.status.conditions[?(@.type=='Ready')].status",
    sort: ["$.status.conditions[?(@.type=='Ready')].status"],
    value: "$.status.conditions[?(@.type=='Ready')].status",
    width: 80,
    align: 'center',
  },
  {
    name: 'schedulable',
    labelKey: 'longhorn.node.table.header.schedulable',
    value: 'spec.allowScheduling',
    sort: 'spec.allowScheduling',
    search: 'spec.allowScheduling',
    formatter: 'CapitalizedValue',
    width: 100,
    align: 'center',
  },
  {
    name: 'replicas',
    labelKey: 'longhorn.node.table.header.replicas',
    value: 'replicas',
    formatter: 'Link',
    width: 80,
    align: 'center',
  },
  {
    name: 'allocated',
    labelKey: 'longhorn.node.table.header.allocated',
    value: 'disksAllocated',
    formatter: 'ConsumptionGauge',
  },
  {
    name: 'used',
    labelKey: 'longhorn.node.table.header.used',
    value: 'disksUsed',
    formatter: 'ConsumptionGauge',
  },
  {
    name: 'size',
    labelKey: 'longhorn.node.table.header.size',
    value: 'disksSize',
    formatter: 'DiskSize',
    width: 200,
    align: 'center',
  },
  {
    name: 'tags',
    labelKey: 'longhorn.node.table.header.tags',
    value: 'spec.tags',
    formatter: 'Tag',
  },
  AGE,
];

export const VOLUMES_HEADER = [
  STATE,
  {
    name: 'health',
    labelKey: 'longhorn.volume.table.header.health',
    value: '$.status.state',
    sort: ['$.status.state', '$.status.robustness'],
    formatter: 'VolumeHealth',
    width: 120,
  },
  NAME_COL,
  {
    name: 'size',
    labelKey: 'longhorn.volume.table.header.size',
    value: '$.spec.size',
    sort: ['$.spec.size'],
    formatter: 'Si',
    align: 'center',
    width: 100,
  },
  {
    name: 'actualSize',
    labelKey: 'longhorn.volume.table.header.actualSize',
    value: '$.status.actualSize',
    sort: ['$.status.actualSize'],
    formatter: 'Si',
    align: 'center',
    width: 100,
  },
  {
    name: 'dataEngine',
    labelKey: 'longhorn.volume.table.header.dataEngine',
    value: '$.spec.dataEngine',
    sort: ['$.spec.dataEngine'],
    align: 'center',
    width: 80,
  },
  {
    name: 'pvPvc',
    labelKey: 'longhorn.volume.table.header.pvPvc',
    value: '$.status.kubernetesStatus',
    formatter: 'VolumePvPvc',
    align: 'center',
    width: 100,
  },
  {
    name: 'namespace',
    labelKey: 'tableHeaders.namespace',
    value: '$.status.kubernetesStatus.namespace',
    sort: ['$.status.kubernetesStatus.namespace'],
    dashIfEmpty: true,
    align: 'center',
    width: 100,
  },
  {
    name: 'node',
    labelKey: 'longhorn.volume.table.header.node',
    value: '$.status.kubernetesStatus',
    formatter: 'VolumeNode',
  },
  {
    name: 'lastBackupAt',
    labelKey: 'longhorn.volume.table.header.lastBackupAt',
    value: '$.status.lastBackupAt',
    sort: ['$.status.lastBackupAt'],
    formatter: 'LiveDate',
    width: 100,
  },
  AGE,
];

export const DISKS_HEADERS = [
  {
    name: 'schedulable',
    labelKey: 'longhorn.node.table.header.schedulable',
    value: 'allowScheduling',
    sort: 'allowScheduling',
    search: 'allowScheduling',
    formatter: 'CapitalizedValue',
    width: 100,
    align: 'center',
  },
  {
    name: 'id',
    labelKey: 'longhorn.node.table.header.diskId',
    value: 'id',
    sort: ['id'],
    width: 200,
  },
  {
    name: 'diskType',
    labelKey: 'longhorn.node.table.header.diskType',
    value: 'diskType',
    width: 100,
  },
  {
    name: 'path',
    labelKey: 'longhorn.node.table.header.path',
    value: 'path',
    sort: ['path'],
    width: 100,
  },
  {
    name: 'replicas',
    labelKey: 'longhorn.node.table.header.replicas',
    value: 'scheduledReplicaCounts',
    formatter: 'Link',
    width: 80,
    align: 'center',
  },
  {
    name: 'allocated',
    labelKey: 'longhorn.node.table.header.allocated',
    value: 'diskAllocated',
    formatter: 'ConsumptionGauge',
  },
  {
    name: 'used',
    labelKey: 'longhorn.node.table.header.used',
    value: 'diskUsed',
    formatter: 'ConsumptionGauge',
  },
  {
    name: 'size',
    labelKey: 'longhorn.node.table.header.size',
    value: 'diskSize',
    formatter: 'DiskSize',
    width: 200,
    align: 'center',
  },
];

export const RECURRING_JOBS_HEADER = [
  STATE,
  NAME_COL,
  {
    name: 'task',
    labelKey: 'longhorn.recurringJob.table.header.task',
    value: '$.spec.task',
    sort: ['$.spec.task'],
    search: '$.spec.task',
  },
  {
    name: 'cron',
    labelKey: 'longhorn.recurringJob.table.header.schedule',
    value: '$.spec.cron',
    sort: ['$.spec.cron'],
    search: '$.spec.cron',
    formatter: 'CronSchedule',
  },
  {
    name: 'retain',
    labelKey: 'longhorn.recurringJob.table.header.retain',
    value: '$.spec.retain',
    sort: ['$.spec.retain'],
    search: '$.spec.retain',
  },
  {
    name: 'concurrency',
    labelKey: 'longhorn.recurringJob.table.header.concurrency',
    value: '$.spec.concurrency',
    sort: ['$.spec.concurrency'],
    search: '$.spec.concurrency',
  },
  {
    name: 'groups',
    labelKey: 'longhorn.recurringJob.table.header.groups',
    value: '$.spec.groups',
    sort: ['$.spec.groups'],
    search: '$.spec.groups',
  },
  {
    name: 'labels',
    labelKey: 'longhorn.recurringJob.table.header.labels',
    value: '$.spec.labels',
    sort: ['$.spec.labels'],
    search: '$.spec.labels',
    formatter: 'KeyValue',
  },
  AGE,
];

export const BACKUP_TARGETS_HEADER = [
  STATE,
  NAME_COL,
  {
    name: 'backupTargetURL',
    labelKey: 'longhorn.backupTarget.table.header.backupTargetURL',
    value: '$.spec.backupTargetURL',
    sort: ['$.spec.backupTargetURL'],
    search: '$.spec.backupTargetURL',
  },
  {
    name: 'credentialSecret',
    labelKey: 'longhorn.backupTarget.table.header.credentialSecret',
    value: '$.spec.credentialSecret',
    sort: ['$.spec.credentialSecret'],
    search: '$.spec.credentialSecret',
  },
  {
    name: 'pollInterval',
    labelKey: 'longhorn.backupTarget.table.header.pollInterval',
    value: '$.spec.pollInterval',
    sort: ['$.spec.pollInterval'],
    search: '$.spec.pollInterval',
  },

  {
    name: 'available',
    labelKey: 'longhorn.backupTarget.table.header.available',
    value: '$.status.available',
    sort: ['$.status.available'],
    search: '$.status.available',
  },
  {
    name: 'lastSyncedAt',
    labelKey: 'longhorn.backupTarget.table.header.lastSyncedAt',
    value: '$.status.lastSyncedAt',
    sort: ['$.status.lastSyncedAt'],
    search: '$.status.lastSyncedAt',
    formatter: 'LiveDate',
  },
  AGE,
];

export const SYSTEM_BACKUPS_HEADER = [
  STATE,
  NAME_COL,
  {
    name: 'version',
    label: 'Version',
    value: '$.status.version',
    sort: ['$.status.version'],
    search: '$.status.version',
  },
  {
    name: 'state',
    label: 'State',
    value: '$.status.state',
    sort: ['$.status.state'],
    search: '$.status.state',
  },

  {
    name: 'lastSyncedAt',
    label: 'LastSyncedAt',
    value: '$.status.lastSyncedAt',
    sort: ['$.status.lastSyncedAt'],
    search: '$.status.lastSyncedAt',
  },
  AGE,
];

export const SYSTEM_RESTORE_HEADER = [
  STATE,
  NAME_COL,
  {
    name: 'version',
    label: 'Version',
    value: 'version',
    sort: ['version'],
    search: 'version',
  },
  {
    name: 'state',
    label: 'State',
    value: '$.status.state',
    sort: ['$.status.state'],
    search: '$.status.state',
  },
  AGE,
];

export const ENGINE_IMAGES_HEADER = [
  STATE,
  NAME_COL,
  IMAGE_NAME,
  {
    name: 'status',
    labelKey: 'longhorn.engineImage.table.header.status',
    value: '$.status.state',
    sort: ['$.status.state'],
    search: '$.status.state',
  },
  {
    name: 'default',
    labelKey: 'longhorn.engineImage.table.header.default',
    value: 'isDefault',
    formatter: 'Checked',
    align: 'center',
  },
  {
    name: 'refCount',
    labelKey: 'longhorn.engineImage.table.header.refCount',
    value: '$.status.refCount',
    sort: ['$.status.refCount'],
    search: '$.status.refCount',
    align: 'center',
  },
  {
    name: 'buildDate',
    labelKey: 'longhorn.engineImage.table.header.buildDate',
    value: 'status.buildDate',
    formatterOpts: { addSuffix: true },
    formatter: 'LiveDate',
    sort: 'status.buildDate',
  },
];

export const INSTANCE_MANAGERS_HEADER = [
  STATE,
  NAME_COL,
  {
    name: 'status',
    labelKey: 'longhorn.instanceManager.table.header.status',
    value: '$.status.currentState',
    sort: ['$.status.currentState'],
    search: '$.status.currentState',
  },
  {
    name: 'type',
    labelKey: 'longhorn.instanceManager.table.header.type',
    value: '$.spec.type',
    sort: ['$.spec.type'],
    search: '$.spec.type',
    align: 'center',
  },
  {
    name: 'data engine',
    labelKey: 'longhorn.instanceManager.table.header.dataEngine',
    value: '$.spec.dataEngine',
    sort: ['$.spec.dataEngine'],
    search: '$.spec.dataEngine',
    align: 'center',
  },
  {
    name: 'node',
    labelKey: 'longhorn.instanceManager.table.header.node',
    value: '$.spec.nodeID',
    sort: ['$.spec.nodeID'],
    search: '$.spec.nodeID',
    formatter: 'NodeName',
  },
  {
    name: 'image',
    labelKey: 'longhorn.instanceManager.table.header.image',
    value: '$.spec.image',
    sort: ['$.spec.image'],
    search: '$.spec.image',
  },
  AGE,
];

export const ORPHANS_HEADER = [
  STATE,
  {
    ...NAME_COL,
    formatter: 'OrphanName',
  },
  {
    name: 'node',
    labelKey: 'longhorn.orphans.table.header.node',
    value: '$.spec.nodeID',
    sort: ['$.spec.nodeID'],
    search: '$.spec.nodeID',
    formatter: 'NodeName',
  },
  {
    name: 'type',
    labelKey: 'longhorn.orphans.table.header.type',
    value: '$.spec.orphanType',
    sort: ['$.spec.orphanType'],
    search: '$.spec.orphanType',
    width: 120,
  },
  {
    name: 'dataName',
    labelKey: 'longhorn.orphans.table.header.dataName',
    value: '$.spec.parameters.DataName',
    sort: ['$.spec.parameters.DataName'],
    search: '$.spec.parameters.DataName',
  },
  {
    name: 'diskName',
    labelKey: 'longhorn.orphans.table.header.diskName',
    value: '$.spec.parameters.DiskName',
    sort: ['$.spec.parameters.DiskName'],
    search: '$.spec.parameters.DiskName',
  },
  {
    name: 'diskPath',
    labelKey: 'longhorn.orphans.table.header.diskPath',
    value: '$.spec.parameters.DiskPath',
    sort: ['$.spec.parameters.DiskPath'],
    search: '$.spec.parameters.DiskPath',
  },
  {
    name: 'instanceName',
    labelKey: 'longhorn.orphans.table.header.instanceName',
    value: '$.spec.parameters.InstanceName',
    sort: ['$.spec.parameters.InstanceName'],
    search: '$.spec.parameters.InstanceName',
  },
  {
    name: 'instanceManager',
    labelKey: 'longhorn.orphans.table.header.instanceManager',
    value: '$.spec.parameters.InstanceManager',
    sort: ['$.spec.parameters.InstanceManager'],
    search: '$.spec.parameters.InstanceManager',
  },
  {
    name: 'dataEngine',
    labelKey: 'longhorn.orphans.table.header.dataEngine',
    value: '$.spec.dataEngine',
    sort: ['$.spec.dataEngine'],
    search: '$.spec.dataEngine',
    align: 'center',
  },
  AGE,
];
